baseURL = "https://digiversidade.netlify.app/"
languageCode = "en-us"
title = "Digiversidade"
enableEmoji = true

DefaultContentLanguage = "en"

[languages]
  [languages.en]
    title = "Digiversidade"
    languageName = "English"
    weight = 1
  [languages.pt]
    title = "Digiversidade"
    languageName = "Português"
    weight = 2
