baseURL = "https://digiversidade.netlify.app/"
languageCode = "en-us"
title = "Digiversidade"
enableEmoji = true
theme = [ "hugo-debugconsole" ]

DefaultContentLanguage = "pt"
defaultContentLanguageInSubdir = "false"

[languages]
    [languages.pt]
        title = "Digiversidade"
        languageName = "Português"
        weight = 1
        contentDir = "content/pt"
    [languages.en]
        title = "Digiversidade"
        languageName = "English"
        weight = 2
        contentDir = "content/en"
