backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img
defaultContentLanguageInSubdir: true

i18n:
  structure: multiple_files
  locales: [en, pt]
  default_locale: en

collections:
  - name: 'blog-pt'
    label: 'Blog (pt-br)'
    folder: 'content/pt/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Subtítulo', name: 'subtitle', widget: 'string', required: false }
      - { label: 'Slug', name: 'slug', widget: 'string', required: true }
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'pt' }
      - { label: 'Banner', name: 'banner', widget: 'image', required: false }
      - { label: 'Data', name: 'date', widget: 'datetime' }
      - { label: 'Texto', name: 'body', widget: 'markdown' }
  - name: 'blog-en'
    label: 'Blog (en)'
    folder: 'content/en/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
      - { label: 'Slug', name: 'slug', widget: 'string', required: true }
      - { label: 'Language', name: 'language', widget: 'hidden', default: 'pt' }
      - { label: 'Banner', name: 'banner', widget: 'image', required: false, }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
